[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'ds-test/=lib/ds-test/src/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@openzeppelin/=lib/openzeppelin-contracts-08/'
]
# See more config options https://github.com/gakonst/foundry/tree/master/config