name: test

on: workflow_dispatch

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Sets up rep
        run: |
          sh ./shell/init.sh
        id: prepare

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Unit tests on main router
        run: |
          forge test -vvv --match-contract MinimaRouterV1Test
        id: test
